#PORT
server.port=8080

# DATABASE
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# CONNECTION POOL
spring.datasource.hikari.pool-name=UrlShortenerProdPool
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# LOGGING
logging.level.root=INFO
logging.level.org.hibernate.SQL=ERROR

# APP CONFIG
app.base-url=https://short.ly
# app.default-expiry-days=30

#JWT CONFIG
jwt.secret=${JWT_SECRET_PROD}
jwt.token.expiry-in-min=${JWT_TOKEN_EXPIRY_PROD}

#Redis
spring.data.redis.host=${REDIS_HOST_PROD}
spring.data.redis.port=${REDIS_PORT_PROD}
spring.data.redis.timeout=${REDIS_TIMEOUT_PROD}
spring.data.redis.password=${REDIS_PASSWORD_PROD}