spring.application.name=url-shortener
spring.profiles.active=prod

server.servlet.context-path=/

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
